/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 *
 * @author igor
 */


@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class DbappTest {

    private static ResultSet rs = null;
    private static EntityManagerFactory emf;

    public DbappTest() throws ClassNotFoundException {
        Class.forName("org.apache.derby.jdbc.ClientDriver");
    }

    @BeforeClass
    public static void setUpClass() {
        prepareTables();
        emf = Persistence.createEntityManagerFactory("dbappPU");
    }

    static String CreateOsoba
            = "CREATE TABLE OSOBA ("
            + "ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT OSOBA_PK PRIMARY KEY, "
            + "MENO VARCHAR(80)"
            + ")";

    static String CreatePredmet
            = "CREATE TABLE PREDMET ( "
            + "KOD VARCHAR(80) CONSTRAINT PREDMET_PK PRIMARY KEY, "
            + "ODBOR VARCHAR(80), "
            + "OSOBA_FK BIGINT references OSOBA(ID) "
            + ")";

    static private void dropTable(Statement st, String table) {
        try {
            st.executeUpdate("DROP TABLE " + table);
        } catch (SQLException ex) {
            System.out.println("" + ex.getMessage());
        }
    }

    static private void prepareTables() {

        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {

            Statement st = con.createStatement();
            System.out.println("IKO dropping ...");

//            dropTable(st, "PREDMETOSOBA");
//            dropTable(st, "OSOBAPREDMET");
//            dropTable(st, "PREDMET_OSOBA");
            dropTable(st, "OSOBA_PREDMET");

            dropTable(st, "PREDMET");
            dropTable(st, "OSOBA");

            st.executeUpdate(CreateOsoba);
            st.executeUpdate(CreatePredmet);

            st.executeUpdate("INSERT INTO OSOBA VALUES (1, 'Adam')");
            st.executeUpdate("INSERT INTO OSOBA VALUES (2, 'Beta')");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P1', null, 1)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P2', 'AI', 1)");

//            st.executeUpdate("INSERT INTO OSOBA_PREDMET VALUES (1, 'P1')");
//            st.executeUpdate("INSERT INTO OSOBA_PREDMET VALUES (1, 'P2')");
//            st.executeUpdate("INSERT INTO OSOBA_PREDMET VALUES (2, 'P1')");

        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.INFO, ex.getMessage());
        }
    }

    // zakladny test mapovania jednoduchych datovych clenov
    @Test
    public void UT010() {
        EntityManager em = emf.createEntityManager();

        // Osoba 
        Osoba o1 = null;
        try {
            o1 = em.find(Osoba.class, 1L);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(o1);
        assertEquals("", "Adam", o1.getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // zakladny test mapovania mapovania enum Titul
//    @Test
//    public void UT011() {
//        EntityManager em = emf.createEntityManager();
//
//        // Osoba 
//        Osoba o1 = null;
//        try {
//            o1 = em.find(Osoba.class, 2L);
//        } catch (Exception e) {
//            fail("CHYBA EX: " + e.getMessage());
//        }
//
//        assertNotNull(o1);
//        assertEquals("", "Beta", o1.getMeno());
//
//        try {
//            em.close();
//        } catch (Exception e) {
//        }
//    }

    // zakladny test mapovania jednoduchych datovych clenov
    @Test
    public void UT011() {
        EntityManager em = emf.createEntityManager();

        // Predmet
        Predmet p1 = null;
        try {
            p1 = em.find(Predmet.class, "P1");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(p1);
        assertNotNull(p1.getPrednasajuci());
        assertEquals("Adam",p1.getPrednasajuci().getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
    }
    
    // zakladny test mapovania enum Odbor
    @Test
    public void UT012() {
        EntityManager em = emf.createEntityManager();

        // Predmet
        Predmet p = null;
        try {
            p = em.find(Predmet.class, "P2");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(p);
        assertEquals("", Odbor.AI, p.getOdbor());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody pocetPrednasok
    @Test
    public void UT020_pocetPrednasok() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPrednasok(em, "Adam");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 2, r);

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody pocetPrednasok
    @Test
    public void UT021_pocetPrednasok() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPrednasok(em, "Beta");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 0, r);

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // pocetPredmetov(em, "Nikto"); TREBA
    @Test
    public void UT03_pocetPrednasok_Neg1() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPrednasok(em, "Nikto");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 0, r);

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody prednasajuci
    @Test
    public void UT04_prednasajuci() {
        EntityManager em = emf.createEntityManager();
        Osoba os1 = null;

        try {
            os1 = DbApp.vyucujuci(em, "P1");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(os1);
        assertEquals("", "Adam", os1.getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    @Test
    public void UT05_prednasajuci_Neg1() {
        EntityManager em = emf.createEntityManager();
        Osoba os1 = null;

        try {
            os1 = DbApp.vyucujuci(em, "Ziadny");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNull(os1);

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody novyPredmet - osoba existuje 
    @Test
    public void UT060_novyPredmet() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;

        try {
            p = DbApp.novyPredmet(em, "Adam", "P3" , null);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(p);        
        assertNotNull(p.getPrednasajuci());        
        assertTrue(1L ==  p.getPrednasajuci().getId());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // kontrola poctu predmetov po pridani predmetu 
    @Test
    public void UT061_pocetPrednasok() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        Query q = em.createNativeQuery("select count(*) from PREDMET where OSOBA_FK=1");
        Integer pocet =(Integer) q.getSingleResult();

        assertEquals("", 3, pocet.intValue());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // treba
    // kontrola prednasajucich
    @Test
    public void UT062_prednasajuci() {
        EntityManager em = emf.createEntityManager();
        Osoba os = null;

        // prednasajuci predmetu P3
        try {
            os = DbApp.vyucujuci(em, "P3");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(os);
        assertEquals("", "Adam", os.getMeno());
        assertNotNull("", os.getPrednasky());
        assertEquals("", 3, os.getPrednasky().size());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novyPredmet - nova osoba - treba
    @Test
    public void UT070_novyPredmetNovaOsoba() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;
        int r = 0;

        try {
            p = DbApp.novyPredmet(em, "Igor", "P4" , null);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertNotNull(p);
//        assertEquals("Bc-1", p.getRocnik());
        assertNotNull(p.getPrednasajuci());
        assertEquals("Igor",p.getPrednasajuci().getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novyPredmet -  kontrola
    @Test
    public void UT071_novyPredmetOsoba() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;
        int r = 0;

        Query q = em.createNativeQuery("select count(*) from PREDMET where KOD='P4'");
        Integer pocet =(Integer) q.getSingleResult();
        assertEquals("", 1, pocet.intValue());
    
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novyPredmet - nova osoba - kontrola
    @Test
    public void UT072_novyPredmetOsoba() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;
        int r = 0;

        Query q = em.createNativeQuery("select count(*) from OSOBA");
        Integer pocet =(Integer) q.getSingleResult();
        assertEquals("", 3, pocet.intValue());
    
        try {
            r = DbApp.pocetPrednasok(em, "Igor");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals("", 1, r);


        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novy predmet - ziadna osoba
    @Test
    public void UT080_novyPredmetZiadnaOsoba() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;
        int r = 0;

        try {
            p = DbApp.novyPredmet(em, null, "P5" , null);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertNotNull(p);
        assertNull(p.getPrednasajuci());
        
        Query q = em.createNativeQuery("select count(*) from PREDMET where KOD='P5' and OSOBA_FK is null");
        Integer pocet =(Integer) q.getSingleResult();
        assertEquals("", 1, pocet.intValue());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // chybne argumenty - mozno zaradit na koniec testov
    @Test
    public void UT90_predmetExistuje() {
        EntityManager em = emf.createEntityManager();
        Predmet p = null;

        try {
            p = DbApp.novyPredmet(em, "Beta", "P1" , null);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertNull(p);

        Predmet pred = em.find(Predmet.class, "P1");
        assertNotNull("", pred);
        assertNotNull(pred.getPrednasajuci());
        assertEquals("", "Adam", pred.getPrednasajuci().getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    @Test
    public void UT99_main() {                   // mozno rozdelit na dva
        EntityManager em = emf.createEntityManager();
        boolean b=false;
        int r = 0;
        Osoba os = null;

        try {
            DbApp.novyPredmet(em, "Hrach", "OOP" , null );
            DbApp.novyPredmet(em, "Mrkva", "VSA" , null);
            DbApp.novyPredmet(em, "Mrkva", "ASOS" , Odbor.AI);
            
            Query q = em.createNativeQuery("select count(*) from PREDMET where KOD='ASOS' and ODBOR='AI'");
            Integer pocet =(Integer) q.getSingleResult();
            assertEquals("", 1, pocet.intValue());

            r = DbApp.pocetPrednasok(em, "Mrkva");
            
            os = DbApp.vyucujuci(em, "VSA");

        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals("", 2, r);
        assertNotNull(os);
        assertEquals("", "Mrkva", os.getMeno());
        assertEquals("", 2, os.getPrednasky().size());

        try {
            em.close();
        } catch (Exception e) {
        }
    }


}
