/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsa;

import dbapp.DbApp;
import dbapp.Predmet;
import dbapp.Ucitel;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.jupiter.api.AfterAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@TestMethodOrder(MethodOrderer.Alphanumeric.class)
public class DbappTest {
    
    private static int BODY;

    private static ResultSet rs = null;
    private static EntityManagerFactory emf;

    public DbappTest() throws ClassNotFoundException {
    }

    @BeforeAll
    public static void setUpClass() {
        BODY=0;
        prepareTables();
        emf = Persistence.createEntityManagerFactory("vsaPU");
    }

    @AfterAll
    static public void tearDown() {
        System.out.println("\nUspesne UnitTesty = " + BODY);
        System.out.println("\nBODY = " + ((BODY<10)?BODY:2*BODY-10));
        System.out.println("");
    }
    
    static String CreateOsoba
            = "CREATE TABLE UCITEL ("
            + "ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT UCITEL_PK PRIMARY KEY, "
            + "MENO VARCHAR(80), "
            + "NARODENY DATE "
            + ")";

    static String CreatePredmet
            = "CREATE TABLE PREDMET ( "
            + "KOD VARCHAR(80) CONSTRAINT PREDMET_PK PRIMARY KEY, "
            + "ODBOR VARCHAR(80) "
            + ")";

    static String CreateOsobaPredmet
            = "CREATE TABLE UCITEL_PREDMET ("
            + "UCITEL_ID BIGINT references UCITEL(ID), "
            + "PREDMET_KOD VARCHAR(80) references PREDMET(KOD), "
            + "PRIMARY KEY (UCITEL_ID, PREDMET_KOD)"
            + ")";

    static private void dropTable(Statement st, String table) {
        try {
            st.executeUpdate("DROP TABLE " + table);
        } catch (SQLException ex) {
            System.out.println("" + ex.getMessage());
        }
    }

    static private void prepareTables() {

        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {

            Statement st = con.createStatement();

            dropTable(st, "UCITEL_PREDMET");
            dropTable(st, "PREDMET");
            dropTable(st, "UCITEL");

            st.executeUpdate(CreatePredmet);
            st.executeUpdate(CreateOsoba);
            st.executeUpdate(CreateOsobaPredmet);

            st.executeUpdate("INSERT INTO UCITEL VALUES (999991, 'Adam', NULL)");
            st.executeUpdate("INSERT INTO UCITEL VALUES (999992, 'Beta', NULL)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P1', 'Ing-1')");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P2', 'Ing-1')");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P3', 'Ing-1')");

            st.executeUpdate("INSERT INTO UCITEL_PREDMET VALUES (999991, 'P1')");
            st.executeUpdate("INSERT INTO UCITEL_PREDMET VALUES (999991, 'P2')");
            st.executeUpdate("INSERT INTO UCITEL_PREDMET VALUES (999992, 'P1')");

        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.INFO, ex.getMessage());
        }
    }
    
    int checkPU(String p) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from UCITEL_PREDMET where PREDMET_KOD='" + p +
                    "'");
            rs.next();
            return rs.getInt(1);
        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.INFO, ex.getMessage());
        }
        return -1;
    }

    // zakladny test mapovania 
    @Test
    public void UT01() {
        EntityManager em = emf.createEntityManager();

        // Osoba 
        Ucitel o1 = null;
        try {
            o1 = em.find(Ucitel.class, 999991L);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(o1);
        assertEquals("Adam", o1.getMeno());       
//        BODY++;

        assertNotNull(o1.getPredmety());
        assertEquals(2, o1.getPredmety().size());
        BODY++;

        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // zakladny test mapovania jednoduchych datovych clenov
    @Test
    public void UT02() {
        EntityManager em = emf.createEntityManager();

        // Predmet
        Predmet p1 = null;
        try {
            p1 = em.find(Predmet.class, "P1");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(p1);
        assertEquals("Ing-1", p1.getOdbor());
//        BODY++;
        
        assertNotNull(p1.getVyucujuci());
        assertEquals(2, p1.getVyucujuci().size());
        
        BODY++;
        
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody pocetPredmetov
    @Test
    public void UT03_pocetPredmetov() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Adam");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(2, r);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }


    // testy metody vyucujuci
    @Test
    public void UT04_vyucujuci() {
        EntityManager em = emf.createEntityManager();
        Set<Ucitel> os1 = null;

        try {
            os1 = DbApp.vyucujuci(em, "P1");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(os1);
        assertEquals(2, os1.size());

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }
    
    // testy metody vyucujuci
    @Test
    public void UT05_vyucujuci() {
        EntityManager em = emf.createEntityManager();
        Set<Ucitel> os2 = null;

        try {
            os2 = DbApp.vyucujuci(em, "P2");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(os2);
        assertEquals(1, os2.size());

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // testy metody pridajVyucujuceho - predmet aj osoba existuju
    @Test
    public void UT06_pridaj() {
        EntityManager em = emf.createEntityManager();
        boolean b = false;

        try {
            b = DbApp.pridajVyucujuceho(em, "P2", "Beta");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertTrue(b);
        // todo kontrola v db
        assertEquals(2,checkPU("P2"));

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // kontrola poctu predmetov
    @Test
    public void UT07_pocetPredmetov() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Beta");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(2, r);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

   @Test
    public void UT08_vyucujuci() {
        EntityManager em = emf.createEntityManager();
        Set<Ucitel> os = null;

        // vyucujuci predmetu P2
        try {
            os = DbApp.vyucujuci(em, "P2");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        // musia teraz byt dvaja
        assertNotNull(os);
        assertEquals(2, os.size());

        // a jeden z nich je Beta
        Ucitel beta = null;
        for (Ucitel o : os) {
            if ("Beta".equals(o.getMeno())) {
                beta = o;
            }
        }
        assertNotNull(beta);

        // Beta teraz uci dva predmety
        assertEquals(2, beta.getPredmety().size());

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    @Test
    public void UT09_pridajOsoba() {
        EntityManager em = emf.createEntityManager();
        boolean b = false;
        int r = 0;

        try {
            b = DbApp.pridajVyucujuceho(em, "P1", "Igor");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertTrue(b);
        // kontrola v db
        assertEquals(3,checkPU("P1"));
        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
}
        
    @Test
    public void UT10_pridajOsoba() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Igor");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals(1, r);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novy predmet - treba. moze sa rozdelit na dva
    @Test
    public void UT11_pridajPredmet() {
        EntityManager em = emf.createEntityManager();
        boolean b = false;
        int r = 0;

        try {
            b = DbApp.pridajVyucujuceho(em, "P99", "Adam");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertTrue(b);
        assertEquals(1,checkPU("P99"));

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // novy predmet - treba. moze sa rozdelit na dva
    @Test
    public void UT12_pridajPredmetCheck() {
        EntityManager em = emf.createEntityManager();
        boolean b = false;
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Adam");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals(3, r);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    @Test
    public void UT13_CheckNovyPredmet() {
        EntityManager em = emf.createEntityManager();
        // Predmet
        Predmet p1 = null;
        try {
            p1 = em.find(Predmet.class, "P99");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(p1);
        assertEquals("BIS", p1.getOdbor());

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    // chybne argumenty - mozno zaradit na koniec testov
    @Test
    public void UT14_pridajNeg() {
        EntityManager em = emf.createEntityManager();
        boolean b = false;

        try {
            b = DbApp.pridajVyucujuceho(em, null, "P99");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertTrue(!b);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

    @Test
    public void UT15_main() {
        EntityManager em = emf.createEntityManager();
        boolean b=false;
        int r = 0;
        Set<Ucitel> z1 = null;

        try {
            DbApp.pridajVyucujuceho(em, "OOP", "Hrach");
            DbApp.pridajVyucujuceho(em, "VSA", "Mrkva");
            DbApp.pridajVyucujuceho(em, "ASOS", "Mrkva");
            b = DbApp.pridajVyucujuceho(em, "ASOS", "Mrkva");

            r = DbApp.pocetPredmetov(em, "Mrkva");
            z1= DbApp.vyucujuci(em, "VSA");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals(2, r);
        assertNotNull(z1);
        assertEquals(1, z1.size());
        assertTrue(b);

        BODY++;
        try {
            em.close();
        } catch (Exception e) {
        }
    }

}
