package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.junit.AfterClass;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class AppTest {
    
    private static int BODY;

    private static ResultSet rs = null;
    private static EntityManagerFactory emf;
    private static Student co;
    private static Predmet cp;

    public AppTest() throws ClassNotFoundException {
        Class.forName("org.apache.derby.jdbc.ClientDriver");
    }

    @BeforeClass
    public static void setUpClass() {
        BODY = 0;
        prepareTables();
        emf = Persistence.createEntityManagerFactory("skolaPU");
    }
    
    @AfterClass
    public static void vysledok() {
        System.out.println("BODY = " + BODY);
    }

    static String CreateOsoba
            = "CREATE TABLE STUDENT ("
            + "ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT STUDENT_PK PRIMARY KEY, "
            + "MENO VARCHAR(80), "
            + "NARODENY DATE "
            + ")";

    static String CreatePredmet
            = "CREATE TABLE PREDMET ( "
            + "KOD VARCHAR(80) CONSTRAINT PREDMET_PK PRIMARY KEY, "
            + "ODBOR VARCHAR(80) "
            + ")";

    static String CreateOsobaPredmet
            = "CREATE TABLE STUDENT_PREDMET ("
            + "STUDENT_ID BIGINT references STUDENT(ID), "
            + "PREDMET_KOD VARCHAR(80) references PREDMET(KOD), "
            + "PRIMARY KEY (STUDENT_ID, PREDMET_KOD)"
            + ")";

    static private void dropTable(Statement st, String table) {
        try {
            st.executeUpdate("DROP TABLE " + table);
        } catch (SQLException ex) {
//            System.out.println("" + ex.getMessage());
        }
    }

    static private void prepareTables() {

        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {

            Statement st = con.createStatement();
            System.out.println("IKO dropping ...");

//            dropTable(st, "PREDMETSTUDENT");
//            dropTable(st, "STUDENTPREDMET");
//            dropTable(st, "PREDMET_STUDENT");
            dropTable(st, "STUDENT_PREDMET");
            dropTable(st, "PREDMET");
            dropTable(st, "STUDENT");

            st.executeUpdate(CreatePredmet);
            st.executeUpdate(CreateOsoba);
            st.executeUpdate(CreateOsobaPredmet);

            st.executeUpdate("INSERT INTO STUDENT VALUES (1, 'Adam', NULL)");
            st.executeUpdate("INSERT INTO STUDENT VALUES (2, 'Beta', NULL)");
            st.executeUpdate("INSERT INTO STUDENT VALUES (3, 'Fero', NULL)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P1', NULL)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P2', NULL)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P3', NULL)");
            st.executeUpdate("INSERT INTO PREDMET VALUES ('P4', 'TK')");

            st.executeUpdate("INSERT INTO STUDENT_PREDMET VALUES (1, 'P1')");
            st.executeUpdate("INSERT INTO STUDENT_PREDMET VALUES (1, 'P2')");
            st.executeUpdate("INSERT INTO STUDENT_PREDMET VALUES (2, 'P1')");

        } catch (SQLException ex) {
            Logger.getLogger(AppTest.class.getName()).log(Level.INFO, ex.getMessage());
        }
    }

    // zakladny test mapovania datovych clenov osoby
    @Test
    public void UT010() {
        EntityManager em = emf.createEntityManager();

        // Student 
        co = null;
        try {
            co = em.find(Student.class, 1L);
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(co);
        assertEquals("", "Adam", co.getMeno());

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    @Test
    public void UT011() {
        assertNotNull("", co.getPredmety());
        assertEquals("", 2, co.getPredmety().size());
        BODY++;
    }

    // zakladny test mapovania datovych clenov predmetu
    @Test
    public void UT020_findPredmet() {
        EntityManager em = emf.createEntityManager();

        try {
            cp = em.find(Predmet.class, "P1");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(cp);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    @Test
    public void UT021_findStudent() {
        assertNotNull("", cp.getStudenti());
        assertEquals("", 2, cp.getStudenti().size());
        BODY++;
    }

    @Test
    public void UT022_checkOdbor() {
        EntityManager em = emf.createEntityManager();

        try {
            cp = em.find(Predmet.class, "P4");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(cp);
        assertNotNull("", cp.getStudenti());
        assertEquals("", 0, cp.getStudenti().size());
        assertEquals("", Odbor.TK, cp.getOdbor());
        BODY++;
    }

    // pocetPredmetov
    @Test
    public void UT030_pocetPredmetov() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Fero");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 0, r);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    // pocetPredmetov
    @Test
    public void UT031_pocetPredmetov() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Beta");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 1, r);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    // pocetPredmetov(em, "Nikto")
    @Test
    public void UT032_pocetPredmetov_neg() {
        EntityManager em = emf.createEntityManager();
        int r = 0;

        try {
            r = DbApp.pocetPredmetov(em, "Nikto");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals("", 0, r);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    // pridajVyucujuceho - existujuci student 
    @Test
    public void UT040_zapisatStudenta() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            DbApp.zapisatStudenta(em, "Fero", "P3");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        try {
            em.close();
        } catch (Exception e) {
        }

        em = emf.createEntityManager();
        int r = 0;
        try {
            r = DbApp.pocetPredmetov(em, "Fero");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals("", 1, r);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    @Test
    public void UT041_zapisatStudenta_checkPredmet() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            cp = em.find(Predmet.class, "P3");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(cp);

        try {
            em.close();
        } catch (Exception e) {
        }

        assertNotNull("", cp.getStudenti());
        assertEquals("", 1, cp.getStudenti().size());
        BODY++;
    }

    // pridajVyucujuceho - novy student
    @Test
    public void UT050_zapisatNovehoStudenta() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            DbApp.zapisatStudenta(em, "Novak", "P2");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        try {
            em.close();
        } catch (Exception e) {
        }

        em = emf.createEntityManager();
        int r = 0;
        try {
            r = DbApp.pocetPredmetov(em, "Novak");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }
        assertEquals("", 1, r);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    // pridajVyucujuceho - neexistuje predmet
    @Test
    public void UT060_zapisatStudenta_neg() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            DbApp.zapisatStudenta(em, "Adam", "ZiadnyPredmet");
        } catch (Exception e) {
            assertEquals("predmet neexistuje", e.getMessage());
            BODY++;
            return;
        }
        fail("neprisla vynimka");
    }

    // pridajVyucujuceho - duplicita
    @Test
    public void UT061_pridaj_duplicita() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            DbApp.zapisatStudenta(em, "Adam", "P1");
        } catch (Exception e) {
            assertEquals("duplicitny zapis", e.getMessage());
            BODY++;
            return;
        }
        fail("neprisla vynimka");
    }

    // pridajVyucujuceho - chybne udaje
    @Test
    public void UT062_zapisatStudenta_null() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            DbApp.zapisatStudenta(em, null, null);
        } catch (Exception e) {
            assertEquals("chybne udaje", e.getMessage());
            BODY++;
            return;
        }
        fail("neprisla vynimka");
    }

    // novyPredmet neg
    @Test
    public void UT080_novyPredmet_existuje() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            pred = DbApp.novyPredmet(em, "P4");
        } catch (Exception e) {
            assertEquals("predmet existuje", e.getMessage());
        }

        try {
            em.close();
        } catch (Exception e) {
        }

        em = emf.createEntityManager();
        // pocet predmetov sa nesmie zmenit
        Query q = em.createNativeQuery("select count(*) from Predmet");
        Object cnt = q.getSingleResult();
        assertEquals(4, cnt);

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

    // novyPredmet
    @Test
    public void UT081_novyPredmet() {
        EntityManager em = emf.createEntityManager();
        Predmet pred = null;

        try {
            pred = DbApp.novyPredmet(em, "NovyPredmet");
        } catch (Exception e) {
            fail("CHYBA EX: " + e.getMessage());
        }

        assertNotNull(pred);
        assertNull(pred.getOdbor());
        assertNotNull(pred.getStudenti());
        assertEquals(0, pred.getStudenti().size());

        try {
            em.close();
        } catch (Exception e) {
        }
        BODY++;
    }

}
