/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbapp;

import banka.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.jupiter.api.AfterAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@TestMethodOrder(MethodOrderer.Alphanumeric.class)
public class DbappTest {

    private static int BODY;

    private static ResultSet rs = null;
    private static EntityManagerFactory emf;

    public DbappTest() throws ClassNotFoundException {
//        Class.forName("org.apache.derby.jdbc.ClientDriver");
    }

    static String CreatePrevod
            = "CREATE TABLE PREVOD ("
            + "ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PREVOD_PK PRIMARY KEY, "
            + "CAS_PREVODU TIMESTAMP, "
            + "SUMA float8, "
            + "NA_ID BIGINT references UCET(ID), "
            + "Z_ID BIGINT references UCET(ID) "
            + ")";

    static String CreateUcet
            = "CREATE TABLE UCET ( "
            + "ID BIGINT CONSTRAINT UCET_PK PRIMARY KEY, "
            + "MAJITEL_ID BIGINT references OSOBA(ID), "
            + "STAV FLOAT8 "
            + ")";

    static String CreateOsoba
            = "CREATE TABLE OSOBA ( "
            + "ID BIGINT CONSTRAINT OSOBA_PK PRIMARY KEY, "
            + "MENO VARCHAR(40), "
            + "BYDLISKO VARCHAR(40)"
            + ")";

    static private void dropTable(Statement st, String table) {
        try {
            st.executeUpdate("DROP TABLE " + table);
        } catch (SQLException ex) {
        }
    }

    static private void createTables() {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            dropTable(st, "OSOBA_UCET");
            dropTable(st, "UCET_OSOBA");
            dropTable(st, "PREVOD");
            dropTable(st, "UCET");
            dropTable(st, "OSOBA");
            st.executeUpdate(CreateOsoba);
            st.executeUpdate(CreateUcet);
            st.executeUpdate(CreatePrevod);
            st.executeUpdate("INSERT INTO OSOBA VALUES (101, 'Fero', null)");

        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.INFO, ex.getMessage());
        }
    }

    static private void prepareTables() throws SQLException {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREVOD");
            st.executeUpdate("DELETE FROM UCET");
            st.executeUpdate("INSERT INTO UCET VALUES (22, 101, 200.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (33, 101, 0.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (44, 101, -200.0)");
//            con.commit();
            con.close();
        }
    }

    static private void prepareTables1() throws SQLException {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREVOD");
            st.executeUpdate("DELETE FROM UCET");
            st.executeUpdate("INSERT INTO UCET VALUES (122, null, 200.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (133, null, 0.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (144, null, 0.0)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (1001, NULL, 10.0, 133, 122)");
//            con.commit();
            con.close();
        }
    }

    static private void prepareTables2() throws SQLException {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREVOD");
            st.executeUpdate("DELETE FROM UCET");
            st.executeUpdate("INSERT INTO UCET VALUES (222, null, 200.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (233, null, 0.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (244, null, 0.0)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (2001, NULL, 10.0, 233, 222)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (2002, NULL, 10.0, 233, 244)");
//            con.commit();
            con.close();
        }
    }

    static private void prepareTables3() throws SQLException {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREVOD");
            st.executeUpdate("DELETE FROM UCET");
            st.executeUpdate("INSERT INTO UCET VALUES (322, null, 200.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (333, null, 0.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (344, null, 0.0)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (3001, NULL, 10.0, 333, 322)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (3002, '2019-06-18 20:20:34.863', 20.0, 344, 322)");
//            con.commit();
            con.close();
        }
    }

    static private void prepareTables4() throws SQLException {

//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREVOD");
            st.executeUpdate("DELETE FROM UCET");
            st.executeUpdate("INSERT INTO UCET VALUES (422, null, 200.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (433, null, 0.0)");
            st.executeUpdate("INSERT INTO UCET VALUES (444, null, 200)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (4001, NULL, 10.0, 433, 422)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (4003, NULL, 20.0, 433, 444)");
            st.executeUpdate("INSERT INTO PREVOD VALUES (4002, '2019-06-18 20:20:34.863', 5.0, 433, 422)");
//            con.commit();
            con.close();
        }
    }

    private int checkPocetPrevodov() {
        int cnt = -1;
//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT count(*) from PREVOD");
            if (rs.next()) {
                cnt = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.SEVERE, ex.getMessage());
        }
        return cnt;
    }

    private String checkTS(Long pid) {
        String r = "xxx";
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT CAS_PREVODU from PREVOD where  ID =" + pid.toString());
            if (rs.next()) {
                r = rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.SEVERE, ex.getMessage());
        }
        return r;
    }

    private void checkFK(Long pid, Long na, Long zu) {
        Long rna = null;
        Long rzu = null;
//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT Z_ID, NA_ID from PREVOD where  ID =" + pid.toString());
            if (rs.next()) {
                rzu = rs.getLong(1);
                rna = rs.getLong(2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.SEVERE, ex.getMessage());
        }
        assertEquals(na, rna);
        assertEquals(zu, rzu);
    }

    private Double checkStav(Long uid) {
        Double d = null;
//        try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app")) {
        try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu")) {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT STAV from UCET where  ID =" + uid.toString());
            if (rs.next()) {
                d = rs.getObject(1, Double.class);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DbappTest.class.getName()).log(Level.SEVERE, ex.getMessage());
        }
        return d;
    }

    @BeforeAll
    public static void setUpClass() throws SQLException {
        BODY = 0;
        createTables();
        emf = Persistence.createEntityManagerFactory("dbappPU");
    }

    @AfterAll
    static public void tearDown() {
        System.out.println();
        System.out.println("BODY = " + BODY);
        System.out.println();
    }
    
    // 1. vytvaranie prevodu
    // Priprava: db obsahuje 3 ucty a ziadny prevod.
    // 1.1 spravne udaje - v db musi vzniknut 1 prevod so zadanymi udajmi a NULL realizovany, porovnat aj vrateny kluc (4b)
    // 1.2 opakovane spravne udaje - kontrola autogenerovaneho kluca - nesmie vratit ten isty kluc a v tabulke musi pribudnut dalsi zaznam (1b)
    // 1.3 zaporna suma - exception CHYBA, ziadne zmeny v db (1b)
    // 1.4 neexistujuci ucet - exception CHYBA (2b)
    // 2. realizacia prevodov.
    // 2.1 DB obsahuje 3 ucty a 1 realizovatelny prevod
    //     Kontrola stavu na uctoch a ts (4b)
    // 2.2 DB obsahuje 3 ucty, 1 realizovatelny prevod a 1 s nedostatocnym stavom na ucte 
    //     kontrola navratovej hodnoty a stavu na uctoch a ts (1b) 
    // 2.3 DB obsahuje 3 ucty, 1 realizovatelny prevod a 1 zrealizovany prevod 
    //     kontrola navratovej hodnoty a stavu na uctoch a ts (1b) 
    // 3. vsetko spolu
    // DB obsahuje 3 ucty, 1 realizovatelny prevod  
    // vytvorPrevod - 2 zrealizovatelne prevody - nesmie spadnut (1b)
    // realizujPrevody - kontrola navratovej hodnoty a stavu na uctoch a ts (2b) 
    private static Long p1 = null;
    
    

    @Test
    public void UT01_prevod1DB_1b() throws SQLException {
        p1 = -1L;
        prepareTables();
        EntityManager em = emf.createEntityManager();
        try {
            p1 = Dbapp.novyPrevod(em, 10.0, 22, 33);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        int r = checkPocetPrevodov();
        assertEquals(1, r);
        BODY++;
    }

    @Test
    public void UT02_prevod1RVal_1b() throws SQLException {
        assertTrue( p1>0 , "kluc <= 0");
        BODY++;
    }

    @Test
    public void UT03_prevod1TS_1b() throws SQLException {
        String ts = checkTS(p1);
        assertNull(ts);
        BODY++;
    }

    @Test
    public void UT04_prevod1FK_1b() throws SQLException {
        checkFK(p1, 33L, 22L);
        BODY++;
    }

//    @Test
    public void UT05_prevod2_1b() throws SQLException {
        Long p2 = -1L;
        EntityManager em = emf.createEntityManager();
        try {
            p2 = Dbapp.novyPrevod(em, 10.0, 22, 33);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        int r = checkPocetPrevodov();

        assertEquals(2, r);
        BODY++;
    }

    @Test
    public void UT06_prevodNizkaSuma_1b() throws SQLException {
        p1 = -1L;
        prepareTables();
        EntityManager em = emf.createEntityManager();
        try {
            p1 = Dbapp.novyPrevod(em, -10.0, 44, 33);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            if (e.getMessage().toLowerCase().startsWith("chybne ud")) {
                BODY++;
                return;
            }
            fail("Neocakacana VYNIMKA: " + e.getMessage());
        }
        fail("Neprisla vynimka o chybnych udajoch");
    }

    @Test
    public void UT07_prevodZlyUcet_2b() throws SQLException {
        p1 = -1L;
        prepareTables();
        EntityManager em = emf.createEntityManager();
        try {
            p1 = Dbapp.novyPrevod(em, 10.0, 9999, 33);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            if (e.getMessage().toLowerCase().startsWith("chybne ud")) {
                BODY++;
                return;
            }
            fail("Neocakacana VYNIMKA: " + e.getMessage());
        }

        fail("Neprisla vynimka o chybnych udajoch");
        
    }


    @Test
    public void UT11_realizuj1RVal_1b() throws SQLException {
        int r = -1;
        prepareTables1();
        EntityManager em = emf.createEntityManager();
        try {
            r = Dbapp.realizujPrevody(em);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(1, r);
        BODY++;
    }

    @Test
    public void UT12_realizuj1TS_1b() throws SQLException {
        String ts = checkTS(1001L);
        assertNotNull(ts);
        assertTrue(ts.length() > 4, "Kratky timestamp: " + ts);
        BODY++;
    }

    @Test
    public void UT13_realizuj1StavZu_1b() throws SQLException {
        Double d = checkStav(122L);
        assertNotNull(d);
        assertEquals(190.0, d, 0.001);
        BODY++;
    }

    @Test
    public void UT14_realizuj1StavNau_1b() throws SQLException {
        Double d = checkStav(133L);
        assertNotNull(d);
        assertEquals(10.0, d, 0.001);
        BODY++;
    }

    @Test
    public void UT21_realizuj2nizkystav_1b() throws SQLException {
        int r = -1;
        prepareTables2();
        EntityManager em = emf.createEntityManager();
        try {
            r = Dbapp.realizujPrevody(em);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(1, r);
//        BODY++;
        
// bolo zakomentovane ?
        String ts1 = checkTS(2001L);
        assertNotNull(ts1);
        assertTrue(ts1.length() > 4, "Kratky timestamp: " + ts1);
        String ts2 = checkTS(2002L);
        assertNull(ts2, ""+ts2);
        
        // dal by sa tiez overit ako sa nezmenil stav na uctoch
        Double d = checkStav(222L);
        assertNotNull(d);
        assertEquals(190.0, d, 0.001);

        d = checkStav(233L);
        assertNotNull(d);
        assertEquals(10.0, d, 0.001);

        d = checkStav(244L);
        assertNotNull(d);
        assertEquals(0.0, d, 0.001);
        BODY++;
    }

    @Test
    public void UT31_realizuj2realizovany_1b() throws SQLException {
        int r = -1;
        prepareTables3();
        EntityManager em = emf.createEntityManager();
        try {
            r = Dbapp.realizujPrevody(em);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(1, r);

        String ts2 = checkTS(3002L);
        assertEquals("2019-06-18 20:20:34.863", ts2);

        String ts1 = checkTS(3001L);
        assertNotNull(ts1, "TS is NULL");
        assertTrue(ts1.length() > 4,"Kratky timestamp: " + ts1);
        BODY++;
    }

    @Test
    public void UT41_realizujRVal_1b() throws SQLException {
        int r = -1;
        prepareTables4();
        EntityManager em = emf.createEntityManager();
        try {
            r = Dbapp.realizujPrevody(em);
            em.clear();
            em.close();
        } catch (Exception e) {
            em.clear();
            em.close();
            fail("CHYBA EX: " + e.getMessage());
        }

        assertEquals(2, r);
        BODY++;
    }

    @Test
    public void UT42_realizujTS_1b() throws SQLException {
        String ts1 = checkTS(4001L);
        assertNotNull(ts1);
        assertTrue(ts1.length() > 4, "Kratky timestamp: " + ts1);
        String ts3 = checkTS(4003L);
        assertNotNull(ts3);
        assertTrue(ts3.length() > 4, "Kratky timestamp: " + ts3);
        BODY++;
    }

    @Test
    public void UT43_realizuj1Stav_1b() throws SQLException {
        Double d = checkStav(433L);
        assertNotNull(d);
        assertEquals(30.0, d, 0.001);
        BODY++;
    }

    @Test
    public void UT44_realizuj1Stav_1b() throws SQLException {
        Double d = checkStav(422L);
        assertNotNull(d);
        assertEquals(190.0, d, 0.001);
        Double d2 = checkStav(444L);
        assertNotNull(d2);
        assertEquals(180.0, d2, 0.001);
        BODY++;
    }

    @Test
    public void UT51_checkORM_1b() throws SQLException {
        p1 = -1L;
        prepareTables();
        EntityManager em = emf.createEntityManager();
        Osoba f = em.find(Osoba.class, 101L);
        assertNotNull(f);
        assertEquals("Fero",f.getMeno());
//        BODY++;
        assertEquals(3,f.getUcty().size());
        BODY++;
    }
    
}
