package dbapp;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;

@TestMethodOrder(MethodOrderer.Alphanumeric.class)
public class DbAppTest {

    private static int BODY;
    private static EntityManagerFactory emf;

    static String CreateUcitel =
            "CREATE TABLE UCITEL ("
            + "ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            + "DTYPE VARCHAR(31), "
            + "MENO VARCHAR(255) NOT NULL UNIQUE"
            + ")";

    static String CreateDocent =
            "CREATE TABLE DOCENT ("
            + "ID BIGINT NOT NULL PRIMARY KEY REFERENCES UCITEL(ID)"
            + ")";

    static String CreatePredmet =
            "CREATE TABLE PREDMET ("
            + "NAZOV VARCHAR(255) PRIMARY KEY, "
            + "PREDNASAJUCI_ID BIGINT REFERENCES DOCENT(ID)"
            + ")";

    static String CreatePredmetUcitel =
            "CREATE TABLE PREDMET_UCITEL ("
            + "CVICENIE_NAZOV VARCHAR(255) REFERENCES PREDMET(NAZOV), "
            + "CVICIACI_ID BIGINT REFERENCES UCITEL(ID)"
            + ")";

    private static Connection getCon() throws SQLException {
        return DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/edudb", "edu", "edu4edu"
        );
    }

    static private void dropTable(Statement st, String table) {
        try {
            st.executeUpdate("DROP TABLE " + table);
        } catch (SQLException ex) {
        }
    }

    static private void createTables() {
        try (Connection con = getCon()) {
            Statement st = con.createStatement();

            dropTable(st, "PREDMET_UCITEL");
            dropTable(st, "PREDMET");
            dropTable(st, "DOCENT");
            dropTable(st, "UCITEL");

            st.executeUpdate(CreateUcitel);
            st.executeUpdate(CreateDocent);
            st.executeUpdate(CreatePredmet);
            st.executeUpdate(CreatePredmetUcitel);

        } catch (SQLException ex) {
            Logger.getLogger(DbAppTest.class.getName()).log(Level.SEVERE, ex.getMessage());
        }
    }

    static private void prepareTables() throws SQLException {
        try (Connection con = getCon()) {
            Statement st = con.createStatement();
            st.executeUpdate("DELETE FROM PREDMET_UCITEL");
            st.executeUpdate("DELETE FROM PREDMET");
            st.executeUpdate("DELETE FROM DOCENT");
            st.executeUpdate("DELETE FROM UCITEL");
        }
    }

    private int count(String table) throws SQLException {
        try (Connection con = getCon()) {
            ResultSet rs = con.createStatement().executeQuery("SELECT COUNT(*) FROM " + table);
            rs.next();
            return rs.getInt(1);
        }
    }

    private String prednasajuciId(String nazov) throws SQLException {
        try (Connection con = getCon()) {
            PreparedStatement ps = con.prepareStatement(
                    "SELECT PREDNASAJUCI_ID FROM PREDMET WHERE NAZOV = ?"
            );
            ps.setString(1, nazov);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getString(1);
            }
        }
        return null;
    }

    private String menoUcitela() throws SQLException {
        try (Connection con = getCon()) {
            ResultSet rs = con.createStatement().executeQuery("SELECT MENO FROM UCITEL");
            if (rs.next()) {
                return rs.getString(1);
            }
        }
        return null;
    }

    @BeforeAll
    public static void setUpClass() throws SQLException {
        BODY = 0;
        createTables();
        emf = Persistence.createEntityManagerFactory("dbappPU");
    }

    @AfterAll
    static public void tearDown() {
        System.out.println();
        System.out.println("BODY = " + BODY);
        System.out.println();
    }

    @Test
    public void UT01_novyPredmetBezUcitela_2b() throws Exception {
        prepareTables();

        EntityManager em = emf.createEntityManager();
        Predmet p = DbApp.novyPredmet(em, "Databazy", null);
        em.clear();
        em.close();

        assertNotNull(p);
        assertEquals("Databazy", p.getNazov());
        assertEquals(1, count("PREDMET"));
        assertEquals(0, count("UCITEL"));
        assertNull(prednasajuciId("Databazy"));

        BODY += 2;
    }

    @Test
    public void UT02_novyPredmetSUcitelom_3b() throws Exception {
        prepareTables();

        EntityManager em = emf.createEntityManager();
        Predmet p = DbApp.novyPredmet(em, "Programovanie", "Novak");
        em.clear();
        em.close();

        assertNotNull(p);
        assertEquals(1, count("PREDMET"));
        assertEquals(1, count("UCITEL"));
        assertEquals(1, count("DOCENT"));
        assertEquals(1, count("PREDMET_UCITEL"));
        assertEquals("Novak", menoUcitela());
        assertNotNull(prednasajuciId("Programovanie"));

        BODY += 3;
    }

    @Test
    public void UT03_duplicita_2b() throws Exception {
        prepareTables();

        EntityManager em = emf.createEntityManager();
        DbApp.novyPredmet(em, "Matematika", "Kovac");

        try {
            DbApp.novyPredmet(em, "Matematika", "Mrkvicka");
            fail("Neprisla vynimka duplicita");
        } catch (Exception e) {
            assertEquals("duplicita", e.getMessage());
        } finally {
            em.clear();
            em.close();
        }

        assertEquals(1, count("PREDMET"));
        assertEquals(1, count("UCITEL"));

        BODY += 2;
    }

    @Test
    public void UT04_nullNazov_2b() throws Exception {
        prepareTables();

        EntityManager em = emf.createEntityManager();

        try {
            DbApp.novyPredmet(em, null, "Novak");
            fail("Neprisla vynimka chyba");
        } catch (Exception e) {
            assertEquals("chyba", e.getMessage());
        } finally {
            em.clear();
            em.close();
        }

        assertEquals(0, count("PREDMET"));
        assertEquals(0, count("UCITEL"));

        BODY += 2;
    }

    @Test
    public void UT05_prazdnyNazov_1b() throws Exception {
        prepareTables();

        EntityManager em = emf.createEntityManager();

        try {
            DbApp.novyPredmet(em, "", "Novak");
            fail("Neprisla vynimka chyba");
        } catch (Exception e) {
            assertEquals("chyba", e.getMessage());
        } finally {
            em.clear();
            em.close();
        }

        assertEquals(0, count("PREDMET"));

        BODY++;
    }
}
